### ISSUE TITLE
tmp file is not multi-thread safe

### ISSUE THREAD

**Issue by DanBuchan** [psipred/merizo_search#5]
the commandline option to provide a temp file name isn't especially multithread safe. At runtime the code should probably append some random ID to the string the user provides.

The user could provide a random tmp file string of their own but at it stands it's not wholly intuitive and there's no reason we should just have a belt and braces approach here

**Comment by shaunmk** [comment]
Thanks for the heads up, this is now fixed in 489246451c9166717fbb1c5914b2985db302fae7.
